### ISSUE TITLE
Reactions Keywords with Whitespaces

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#112]
Several keywords in the Reactions language contain whitespaces. This produces warnings because the parser is not able to distinguish keywords if one is prefix of another, independent from the context in which they are used.
Recently, this was a problem for the keyword `execute` within an actions block and `execute actions in` in the file header.
We should think about simplifying the keywords to avoid such problems. The `execute` problem is currently solved by splitting `execute actions in` into two keywords, which is generally problematic if the keyword is used often, as the automatically generated content assist is not very helpful anymore.

**Comment by jGleitz** [comment]
I want to add to the discussion that when splitting the parts of keywords, there will be more keywords, which means less names that can be chosen for variable names.

Apart from that, it would be easy to adapt the proposals so they propose combinations that make sense.

**Comment by HeikoKlare** [comment]
> I want to add to the discussion that when splitting the parts of keywords, there will be more keywords, which means less names that can be chosen for variable names.

That's a really good argument against splitting the keywords, thank you! We already had to split some  keywords to allow the greedy parser to correctly handle them. Nevertheless, we should keep the others as they are to avoid reducing the space of usable variable names by further keywords.

In consequence, I would propose to close this issue without any changes.
