### ISSUE TITLE
Asserted retrievals in Reactions

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#143]
Reactions currently support an ordinary element retrieval from the correspondence model, as well as an optional one. While the former retrieves and element and aborts the routine execution if there is no element, the latter returns null if there is no corresponding element.

Since in some cases, the retrieval should not determine if the routine has to be executed or not, but is mandatory because the consistency specifications require the correspondence to always exist when reaching the routine, it would be helpful to have a definition of this expected behavior so that testing and debugging is more easy.

We therefore propose a kind of "asserted" retrieve, which leads to an exception if the retrieve operations fails.
Finally, this will lead to three kinds of retrieval, for which we have to find concise names, such as
- `retrieve asserting`
- `retrieve matching`
- `retrieve optional`

**We would be glad to get proposals for better keywords.**

The first to properties will also be attached to check operations in a Reactions matcher.

**Comment by HeikoKlare** [comment]
Applying the proposal to our case studies has shown to me, that adding another keyword to the default case (matching) is no good idea.
Since most of the statements are matching retrievals, it is unnecessary additional effort, and the keyword itself is not very precise, as it often sound like any matching element is retrieved. Since we are in the _match_ block, the default behavior can be assumed to be a match. Therefore, we will keep the old syntax, just extended by an `asserted` case.

Finally, we will have three cases, which are the default case, a more restricted `asserted` can and a less restricted `optional` case.

**Comment by jGleitz** [comment]
I might add that from my intuition, I expected the default case to behave like the proposed `retrieve asserting` will. But I see the point that the `matching` case is the one that is needed most often.

**Comment by jGleitz** [comment]
> and the keyword itself is not very precise

`retrieve required` would be a more expressive alternative imo.

**Comment by HeikoKlare** [comment]
Due to the semantics of the _match_ block, the `matching` case is not only the mostly needed but also semantically the default case. Nevertheless, the semantics of the language is not specified very well, so no one will know what the intended semantics is.
We also discussed `required` as a potential keyword, but we feat that it's unclear whether it is _required_ to proceed with the routine execution or _required_ to proceed at all (or throw an exception). So it might not be intuitively distinguished from `asserted`.

**Comment by jGleitz** [comment]
I think those are very good arguments for not having a modifier for the default case.

Consistency Preservation is way too complicated to expect that a DSL for it can be understood without any further explanation. So there will probably always be some ambiguity, regardless of how the concrete syntax looks like.

**Comment by HeikoKlare** [comment]
That's right. And thanks for your approval!
