### ISSUE TITLE
Error when saving a model in the default tree editor

### ISSUE THREAD

**Issue by SofiaAnanieva** [vitruv-tools/Vitruv#176]
I am testing the consistency mechanisms on a model created by the EMF default tree editor. When performing any change via the editor and saving the model, an IllegalStateException occurs. This is due to the fact, that the eObject is null when the UuidGeneratorAndResolver tries to retrieve the EObject. I am currently investigating the VitruviusEMFBuilder.  Along the way I noticed that the VURI of the model becomes null at some point. I don't know if this is somehow connected to the error.

**Comment by FabiScheytt** [comment]
216038158c1ab2d2d61fc9db9524868d2c7afc06 should solve our issue as the globalUuidResolver can now be resolved from the virtualModel during initialisation (of EMFModelChangeRecordingEditorSaveListener).
@HeikoKlare maybe someone from the team can take a short look and confirm that the line wasn't deliberately placed at the end of the function.
