### ISSUE TITLE
VitruviusApplicationTest doesn't propagate changes back to the original model

### ISSUE THREAD

**Issue by FabiScheytt** [vitruv-tools/Vitruv#177]
When using the same model as source and target within a _VitruviusApplicationTest_ changes from the reactions are propagated to the virtual model but not the original model.

The same process works fine within the _VitruviusEmfBuilder_ and the model editor .

**Comment by HeikoKlare** [comment]
What is the _original_ model in this case? The one that was modified in the `ResourceSet` of the `VitruviusApplicationTest`?
This mechanisms is currently not supported by the Test class. You would have to perform a reload of the appropriate `Resource` after propagating a change, which could potentially result in problems with the UUID mechanism.

**Comment by jGleitz** [comment]
I have found this issue some weeks ago, too and talked to @HeikoKlare about it. I think he made a good point: The `ResourceSet` in `VitruviusApplicationTest` must be seen as a view on the VSUM. And we do not yet have a proper strategy regarding how to reflect changes to the VSUM in loaded views (it might not always be appropriate to replace the editor content while a user is working on it).

That being said, I developed some helpers for my tests. I shared the latest changes to them in #178. From my point of view, they allow specifying assertions on models nicely, while always loading the models from disk. See my [`IdentifiedExecutionTest`](https://github.com/jGleitz/Vitruv/blob/commonalities/tests/dsls/tools.vitruv.dsls.commonalities.ui.tests/src/tools/vitruv/dsls/commonalities/ui/executiontests/IdentifiedExecutionTest.xtend#L115) for an example. Maybe this also helps for your use cases.

**Comment by HeikoKlare** [comment]
Is this issue still relevant and is there some idea how to fix it or are the extensions made by @jGleitz sufficient to solve your problem?

**Comment by SofiaAnanieva** [comment]
Many thanks for the greatly helping answers! We will examine the Test Helpers from @jGleitz in the next step and come back in case of questions.

**Comment by FabiScheytt** [comment]
The changes introduced in #178 should be fine enough for asserting JUnit tests. Thanks for the help!
