### ISSUE TITLE
UUID model persistence

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#298]
It seems like the UUID model is currently not persisted (in the `uuid` folder of the V-SUM project), although a resource is properly created for it within the `UuidGeneratorAndResolverImpl`.
In the `ResourceRepositoryImpl`, there is only explicit persistence for the correspondence model but not for the UUID model, which may be the problem.

**Comment by HeikoKlare** [comment]
The problem with this persistence is that the `UuidRepository` references elements from other models, of which not all seem to be persisted, which then leads to exceptions during serialization.
We have to investigate why there are elements that are not persisted (maybe this is because they were deleted?)

**Comment by jGleitz** [comment]
> (maybe this is because they were deleted?)

would fit too #425

**Comment by HeikoKlare** [comment]
>would fit to #425

May be, but that one concerns correspondences and not object UUIDs. I would expect those correspondences to be orphans, as they are not accessible due to the impossibility to resolve the UUIDs of the correspondence after removing the elements. But maybe the UUIDs are still resolvable and then, of course, both issues are interrelated.
