### ISSUE TITLE
Reactions code generator cannot handle nsURIs of the form http://asinglewordwithoutdot

### ISSUE THREAD

**Issue by max-kramer** [vitruv-tools/Vitruv#31]
If a metamodel with a nsURI of the form http://asinglewordwithoutdot is used in a reaction, then the code generator tries to generate code in a package with a name that contains the complete nsURI and thus fails because of the ":"

**Comment by HeikoKlare** [comment]
I tested this with an appropriate URI (http://wwwexampleorg) and found no problems.
Potentially, this issue was implicitly solved by one of the changes/refactoring/fixes in the Reactions language during the last months.
