### ISSUE TITLE
Allow collection retrieval in Reactions

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#36]
Reactions do only allow the retrieval of a single element in the matcher.
Sometimes it is necessary to retrieve a collection of elements, as it is only know that an element corresponds to an arbitrary number of elements of a certain type. For example, in the families-persons scenario, a person in the persons modelcan be member of several families in the families model (e.g. one son and several fathers). Assuming that it is allowed to be father in several families, it is not possible to restrict the retrieval to a single member with the "with"-condition. 

We have to possibilies to integrate such a retrieval into the reactions:
1. We allow to specify "retrieve collection of ..." statements that write the collection of elements to the specified variable, which can be processed within the routine.
2. We allow to specify a single "retrieve collection of..." statement per routine, which results in the execution of the routine for each of the elements in the collection.

Which behavior is more reasonable? The second one assumes that a consistency relation does only contain a static number of elements, thus of you retrieve a collection, each of the elements in the collection belongs to a single consistency relation, which you can restore in one routine execution. The first possibility is more flexible and should thus be only used if we think that it is possible to have one consistency relation which all these elements belong to, so that it is necessary to be able to reference all of them in one routine execution.

**Comment by max-kramer** [comment]
I suggest to realize the first option and to communicate the best practice of having routines for individual elements that are called from a call block with a for-each loop.

**Comment by SofiaAnanieva** [comment]
Currently working with FZI HiWi @FabiScheytt on this topic. We also go for the first option and will keep you updated with the progress.
