### ISSUE TITLE
Commonalities Generation is Entirely Broken when Run in a Real Eclipse

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#367]
When I edit any of the Commonalities in the CBS application from my inner Eclipse instance (version 02020-12), I get errors as soon as Eclipse tries to build it. The errors vary, from types not being determined correctly to the very helpful error message ‘Generating Code’

**Comment by HeikoKlare** [comment]
Hm, that is strange. Although the generated code has some errors (which do not seem to be relevant as the faulty parts are not executed), the code generation works fine in my inner Eclipse (also version 2020-12). Maybe this is a system-specific / OS-specific problem. Did the compilation stop working recently or didn't you try for a while?

**Comment by jGleitz** [comment]
It only seems to happen if ‘Build Automatically’ is enabled. It does not happen when building manually.

**Comment by jGleitz** [comment]
It seems this is mostly fixed by now, although the Commonalities generation process is still quite susceptible to inconsistent states.
