### ISSUE TITLE
PropagatedChangeListener Wrongly Assumes that a ProgatedChange Only Affects One Domain

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#416]
[`PropagatedChangeListener`](https://github.com/vitruv-tools/Vitruv/blob/releases/2.0.1/bundles/framework/tools.vitruv.framework.vsum/src/tools/vitruv/framework/vsum/PropagatedChangeListener.xtend)’s API wrongly assumes that a [`PropagatedChange`](https://github.com/vitruv-tools/Vitruv/blob/releases/2.0.1/bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/PropagatedChange.xtend) can only affect one domain. This wrong. While we currently only support that the _source_ changes affect only one domain (a restriction that will have to be dropped at some point in the future), the _target_ changes can already affect multiple domains.

We currently bridge this gap by having [`ChangeDomainExtractor`](https://github.com/vitruv-tools/Vitruv/blob/releases/2.0.1/bundles/framework/tools.vitruv.framework.vsum/src/tools/vitruv/framework/vsum/helper/ChangeDomainExtractor.xtend) pick the first affected domain and report that as `targetDomain`.

The only [`PropagatedChangeListener`](https://github.com/vitruv-tools/Vitruv/blob/releases/2.0.1/bundles/framework/tools.vitruv.framework.vsum/src/tools/vitruv/framework/vsum/PropagatedChangeListener.xtend) I could find is [`ChangeVisualization`](https://github.com/vitruv-tools/Vitruv/blob/releases/2.0.1/bundles/extensions/changevisualization/tools.vitruv.extensions.changevisualization/src/tools/vitruv/extensions/changevisualization/ChangeVisualization.java). It needs to be adapted to handle multiple affected domains.

Going forward, I think it would be useful to have a type `DomainCompositeChange` which simply stores the unique domain that all its inner changes affect. A [`PropagatedChange`](https://github.com/vitruv-tools/Vitruv/blob/releases/2.0.1/bundles/framework/tools.vitruv.framework.change/src/tools/vitruv/framework/change/description/PropagatedChange.xtend)’s `consequentialChanges` could then be a `Map<VitruvDomain, DomainCompositeChange>`. This proposal is currently impossible because @HeikoKlare insists that domains may not leave the VSUM. For me, it’s another proof that Vitruv needs a type to represent the concept of a ’domain’. I think it would be fine to simply us `VitruvDomain` for that.

**Comment by HeikoKlare** [comment]
This became obsolete with #538.
