### ISSUE TITLE
One Resource Set per Domain in ResourceRepositoryImpl

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#440]
The `ResourceRepositoryImpl` currently manages a resource set containing all domain models. Only the correspondence model is separated into an additional resource set. However, for each resource a proper domain recorder has to be registered, because different recorders track changes for the different domains. It would be beneficial to manage one resource set per domain such that we can register a recorder for the complete resource set instead of deciding for each resource on its own. This is currently problematic because the `UuidGeneratorAndResolverImpl` uses a resource containing the UUIDs and references to the according `EObjects` and thus has to be placed in the domain models' resource set. Having one resource set per domain would best come along with one `UuidGeneratorAndResolverImpl` per domain. This will be possible as soon as UUID handling is hidden in the V-SUM and no resolver is provided by the `VirtualModel` anymore. Then, it should be possible to perform the discussed separation of domain models into domain-specific resource set.
See also the discussion in #439.

**Comment by JanWittler** [comment]
I would propose to close this issue as it is outdated? As we removed the domains, I don't think there is anything left to do here @HeikoKlare ?
With recent refactoring, the `ResourceRepositoryImpl` now has different recorders based on file ending instead of domains.

**Comment by HeikoKlare** [comment]
Actually, the domains were only used to retrieved file extensions that belong together to instantiate a common change recorder. Thus, we could still address this issue by setting up one resource set per file extension. The question is, however, whether that enhancement is worth the effort, since we currently have no problems putting all models into the same resource set. It would just simplify the functionality for attaching change recorders to resources, as we can then simply monitor a complete resource set rather than monitoring resource additions to apply the appropriate recorder.

**Comment by JanWittler** [comment]
Having a look at the source code, I am wondering why we even use different recorders for each file extension? Why not one recorder for the entire resource set? Even if the assumption holds that each file extension uniquely identifies a domain (which does obviously not), what would be the benefit of having one change recorder per domain instead of one for all domains?

Anyways, I would strongly vote against having one resource set per file extension, as this will lead to problems with element resolution as soon as a model references another element in a model with a different file extension.

**Comment by HeikoKlare** [comment]
True, so I absolutely agree to closing this issue.

Regarding one recorder per file extension: This is "necessary" to generate one change per "domain", i.e., per file extension / metamodel, such that we can use that change to execute the `ChangePropagationSpecifications` for that metamodel. Otherwise there would only be a bunch of changes that need to passed to all `ChangePropagationSpecifications` without having a proper separation betwen the metamodels. Probably that would still work, but having a clear separation still makes sense in my opinion.
