### ISSUE TITLE
Allow updating modified views from their underlying sources

### ISSUE THREAD

**Issue by tsaglam** [vitruv-tools/Vitruv#490]
Currently, a view cannot be updated from its sources if it is modified. This means the modifications on the view need to be committed to the sources, or the modified view needs to be discarded and regenerated from the viewpoint.

https://github.com/vitruv-tools/Vitruv/blob/d8c9da5c3e77a67e63ac99cd6bde0054599a9809/bundles/framework/tools.vitruv.framework.vsum/src/tools/vitruv/framework/vsum/views/View.java#L49-L60

It would be better to allow updating modified views, i.e., by re-applying the uncommitted changes to an updated state from the sources, thus resulting in an updated view with the modification present. This, however, might not always be possible, as changes to the sources might conflict with changes to the view.

**Comment by TomWerm** [comment]
Currently it is not planned to provide model transformations for changes applicable to a V-SUM to changes applicable to a view.
