### ISSUE TITLE
Missing Tests for the Insertion of Multiple Elements into an EReference

### ISSUE THREAD

**Issue by NeumannDirk** [vitruv-tools/Vitruv#507]
A test class for the insertion of emelents into an `EReference` does exist [here](https://github.com/vitruv-tools/Vitruv/blob/master/tests/framework/tools.vitruv.framework.change.tests/src/tools/vitruv/framework/tests/change/reference/ChangeDescription2InsertEReferenceTest.xtend), but it does not yet contain tests for the insertion of multiple elements at once in the form of `record [ eReference.addAll(listOfElements) ]`. This test should be included to evolve from there to future more sophisticated tests concerning planned functionality of making Change-Sequences more independent from possible modifications after recording such as deleting changes from the sequence.

**Comment by JanWittler** [comment]
@NeumannDirk Can this ticket be closed due to #509 ?

**Comment by NeumannDirk** [comment]
Yes
