### ISSUE TITLE
Make change visualization V-SUM independent

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#532]
The change visualization (`tools.vitruv.extensions.changevisualization`) currently depends on a V-SUM and the used `VitruvDomains`. The visualization does, however, only visualize the propagation of changes and should thus be applied to a `ChangePropagator`. In addition, the `ChangeVisualization` uses a `PropagatedChangeListener` interface, which pollutes the `VitrtualModel` interface although there already is a `ChangePropagationListener` interface, which also leads to confusion because of the similar naming.
To this end, we have to refactor the `ChangeVisualization` implementation:
- [x] Refactor or remove the `PropagatedChangeListener`, either by renaming it and making it independent from V-SUM concepts, or, even better, remove it and integrate the functionality into the `ChangePropagationListener`.
- [x] Adapt the `ChangeVisualization` to the modified/removed `PropagatedChangeListener` interface
- [x] Make `ChangeVisualization` (and the project around it) independent from V-SUM concepts
- [x] Refactor the code in the `tools.vitruv.extensions.changevisualization` project to conform to our stands
- [x] Move the `tools.vitruv.extensions.changevisualization` project to the [Vitruv-Change](https://github.com/vitruv-tools/Vitruv-Change) repository

This issue has already been discussed in https://github.com/vitruv-tools/Vitruv/pull/529#issuecomment-1160088499 and https://github.com/vitruv-tools/Vitruv/pull/529#issuecomment-1160117497.

**Comment by JanWittler** [comment]
Relates to #416

**Comment by HeikoKlare** [comment]
Done in #548.
