### ISSUE TITLE
Make VSUM Eclipse-independent

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#57]
The VSUM mechanisms currently rely on Eclipse mechanisms such as the workspace and projects within it.
This makes Vitruv strongly tied to Eclipse although that is not necessary (in my opinion).

We could manage the VSUM in a specific folder, which is not necessarily an Eclipse project. There could be an extended version of the VSUM that is an Eclipse project or it could be generated by the UI/Wizard as an Eclipse project. The builder mechanisms that propagates changes to the VSUM using specific project builders would also be part of the Vitruv UI then.
That way, the Vitruv mechanisms get independent from Eclipse and especially tests can be written without relying on Eclipse and the necessity to run them as plugin tests instead of oridinary Junit tests.

**Comment by HeikoKlare** [comment]
The VSUM was already made Eclipse-independent by a previous commit.
What is missing is the integration into the UI/ a wizard.

**Comment by HeikoKlare** [comment]
UI integration is also complete.

What is still missing: Running all application tests as non-plugin-tests. There are still some problems that we have to solve.

**Comment by jGleitz** [comment]
The VSUM tests now run without an Eclipse Platform. Application tests _can_ be run without a platform, even though not all existing tests support it and may need to be adapted.

I propose to close this ticket as the relevant work on the framework is done. If individual tests should be change to become independent of Eclipse, we should open a ticket for those tests.
