### ISSUE TITLE
Checkstyle Usage

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#74]
Which formatting guidelines should be followed by code in this project? Specifically, Checkstyle is set up for `tools.vitruv.framework.userinteraction`, using the Google Coding Conventions. However, the project does not adhere to these guidelines by any means. No other project is set up to use Checkstyle.

**Comment by HeikoKlare** [comment]
The projects do not adhere to specific formatting guidelines. The Checkstyle setup is outdated.
We have not yet tested Checkstyle with Xtend, which would be necessary as it is our primary programming language.

**Comment by jGleitz** [comment]
Doing a quick search on the Internet, I did not find and Linting tool for Xtend.

We could however set a common Formatter configuration on the projects and publish that configuration somewhere so that in can be used for new projects. That would at least provide some degree of uniformity.

I don’t know if code formatting is an issue after all. I never saw anything that was particularly bad formatted and until now never had issues with whitespace-only changes. I only wanted to mention that possibility.

**Comment by HeikoKlare** [comment]
I use the Eclipse built-in formatter for Java and the default formatter deployed with and for Xtend.
I dont't know if we really need an additional configuration. As you said, formatting does not seem to be an issue after all.
If anyone discovers a tool that supports Xtend well, we could think about using it.

**Comment by jGleitz** [comment]
As we seem to agree on this matter,  #86 will close this issue
