### ISSUE TITLE
getNsUris is in TuidAwareVitruvDomain

### ISSUE THREAD

**Issue by jGleitz** [vitruv-tools/Vitruv#83]
From the code I see that `TuidAwareVitruvDomain#getNsUris` returns the Namespace URIs used by any metamodel of a domain. However, only a `VitruvDomain` knows about metamodels, a `TuidAwareVitruvDomain` does not. So shouldn’t `getNsUris` be in `VitruvDomain`?

**Comment by HeikoKlare** [comment]
That's right. I will move that method (and also the `isInstanceOfDomainMetamodel method`). 
The essential problem is the faulty inheritance hierarchy: Actually, a `TuidAwareVitruvDomain` should be a subclass of the general `VitruvDomain` but it is vice versa due to somethink I cannot remember...
