### ISSUE TITLE
Build against Xtext/Xtend 2.12

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#87]
Also we have specified Xtend/Xtext version 2.10 everywhere (because Eclipse Neon.3 has a hard dependency to that version), Maven compiles with Xtend 2.12, so that the `apply` method of the `StringConcatention` has a different signature, leading to execution errors.

We have to find out how to build with Xtend 2.10 or how we can depend on Xtend 2.12 everywhere without conflicting with standard Eclipse dependencies (last would be best).

**Comment by jGleitz** [comment]
> because Eclipse Neon.3 has a hard dependency to that version

I don’t think that’s true. I had Xtend 2.12 installed in my Neon.3

**Comment by HeikoKlare** [comment]
That's interesting. Did you use the Eclipse Modeling Tools package or another one? 
The Modeling Tools contain Eclipse Parsley, which has a hard dependency to Xtend 2.10, making it impossible to install any other Xtend version. Some time ago, they changed that hard dependency to Xtend 2.11 oder 2.12, but revoked that change recently.

**Comment by jGleitz** [comment]
I see. My Eclipse Neon was (I just updated to Oxygen today) the Standard Java Development Tools distribution into which I installed EMF, Xtext and Xtend by hand through their Update Sites. It’s quite likely that I did not have Eclipse Parsley installed, which would explain why I did not have that problem.

**Comment by HeikoKlare** [comment]
Okay, that explains why it worked for you.
But thank you for your issue #88. I will test Vitruv with the Modeling Tools package of Oxygen as it uses Xtend 2.12 by default. Maybe we can then build against Oxygen to finally get around the (really serious) problems that we have with the broken dependencies from and to Xtend.
