### ISSUE TITLE
Remove changesequenceimporter.tests

### ISSUE THREAD

**Issue by HeikoKlare** [vitruv-tools/Vitruv#90]
The project is tools.vitruv.framework.changesequenceimporter.tests is a prototype project for testing change sequence import, it is neither a productive bundle, nor compiles it due to unresolved dependencies (to the CAEX metamodel). It should be removed or converted into a productive bundle with correct dependencies and provided funtctionality.

**Comment by SofiaAnanieva** [comment]
Removed the project from the framework
